### ISSUE TITLE
SpecUtil 0.2.2 Dependency 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#117]
Currently MOSViz is dependent on SpecUtil==0.2.2. Its only available with `pip` as of now. We should think about updating to the current version.

**Comment by nmearl** [comment]
MOSViz should not be using specutils 0.2.2 this sprint. The effort last week was to bring specutils up to version 0.4 and have a release, but we do have some [lingering blockers](https://github.com/astropy/specutils/milestone/3) that we hope to have done today(!).

**Comment by robelgeda** [comment]
```
Traceback (most recent call last):
  File "/Users/rgeda/miniconda3/envs/mosviz/bin/mosviz", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/rgeda/miniconda3/envs/mosviz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/Users/rgeda/miniconda3/envs/mosviz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/Users/rgeda/miniconda3/envs/mosviz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/rgeda/miniconda3/envs/mosviz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/rgeda/miniconda3/envs/mosviz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/rgeda/miniconda3/envs/mosviz/lib/python3.5/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'specutils==0.2.2' distribution was not found and is required by mosviz
```
