### ISSUE TITLE
Invalid specutils import

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/mosviz#62]
Perhaps `specutils.core` was deprecated upstream?

===== testing package: mosviz-0.0.dev391-26_g2213690_0 =====
import: 'mosviz'
Traceback (most recent call last):
  File "/home/jhunk/anaconda3/conda-bld/mosviz_1498595392597/test_tmp/run_test.py", line 27, in <module>
    import mosviz
  File "/home/jhunk/anaconda3/conda-bld/mosviz_1498595392597/_t_env/lib/python3.5/site-packages/mosviz/__init__.py", line 18, in <module>
    from . import viewers
  File "/home/jhunk/anaconda3/conda-bld/mosviz_1498595392597/_t_env/lib/python3.5/site-packages/mosviz/viewers/__init__.py", line 3, in <module>
    from .mos_viewer import *
  File "/home/jhunk/anaconda3/conda-bld/mosviz_1498595392597/_t_env/lib/python3.5/site-packages/mosviz/viewers/mos_viewer.py", line 16, in <module>
    from specutils.core.generic import Spectrum1DRef
ImportError: No module named 'specutils.core'
TESTS FAILED: mosviz-0.0.dev391-26_g2213690_0

**Comment by nmearl** [comment]
Thanks @jhunkeler. I'll push a fix soon -- I've wiped the old specutils repo given the new efforts to fix it, but I haven't made any changes to the pypi package. We're preserving the old specutils in the `legacy-specutils` branch, but perhaps, if it's being included through astroconda, it's probably pulling from the repo and not pypi. I'll be sure to add some requirements to the anaconda build file to make sure it's looking at that branch.

**Comment by nmearl** [comment]
@jhunkeler Well, actually, this is strange. Looking at the specutils package build instructions, it seems like it's building v0.2.1 from the tagged release into astroconda. I'd assume mosviz is looking to the astroconda specutils version. In that case, it ought to be fine...
